In [12]:
a = 255
b = 254
print(a.to_bytes(1, byteorder='big', signed=False)+ b.to_bytes(1, byteorder='big', signed=False))

b'\xff\xfe'


In [39]:
if 1==1:
    print(1)

1


In [36]:
dtype = 'int64'
import sys

In [41]:
dshape = (80,80,3)
print(dshape)

(80, 80, 3)


In [45]:
res = np.random.randint(10,240, size=(640, 640,3))
byteRes = res.tobytes()
print(sys.getsizeof(byteRes))
# dtype = res.dtype.name
dshape = res.shape
print(dtype)
# print(res)

9830433
int64


In [43]:
print(recons)

[[[ 95 234 143]
  [139 137  83]
  [ 42  44 166]
  ...
  [177 106  75]
  [193  83 226]
  [205  89 223]]

 [[121  95 149]
  [ 27 114 145]
  [125  37 192]
  ...
  [199  53 152]
  [231  65 217]
  [177  84 184]]

 [[138  50  44]
  [231 152  24]
  [222 177 121]
  ...
  [121 233 231]
  [118  42 197]
  [223 200 211]]

 ...

 [[ 63 164 225]
  [166  45  26]
  [ 21  98 234]
  ...
  [ 87  39 197]
  [ 11 182  56]
  [ 76 122 148]]

 [[172  14 148]
  [217  82  96]
  [206  62  34]
  ...
  [113 208  42]
  [201  41  73]
  [236 135 235]]

 [[208  39 226]
  [ 35 181 188]
  [ 66  24 186]
  ...
  [199 104  74]
  [ 84  76  39]
  [ 54 211 174]]]


In [42]:
recons = np.frombuffer(byteRes,dtype=dtype).reshape(dshape)

In [29]:
import numpy as np
res = np.random.randint(0,11, size=(80, 80,3))
for i in (j for j in (k for k in res)):
    print(j)

[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
[10  4  0]
